





































}  )    </div>      </main>        </div>          </div>            </Link>              View Menu            >              className="inline-block mt-4 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 transform hover:scale-105 active:scale-95"              href="/menu"            <Link            </p>              local ingredients, we create delicious dishes that celebrate our culinary heritage.              True North Bites is dedicated to bringing the best of Canadian fast food to our community. Using fresh,            <p className="text-gray-700 leading-relaxed">            <h2 className="text-3xl font-bold mb-4">Our Story</h2>          <div className="md:w-1/2 md:pl-12">          </div>            />              className="rounded-lg shadow-lg w-full h-auto"              height={400}              width={600}              alt="True North Bites interior"              src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1470&q=80"            <Image          <div className="md:w-1/2 mb-8 md:mb-0">        <div className="flex flex-col md:flex-row items-center">        <h1 className="text-4xl font-bold mb-8 text-center">About Us</h1>      <main className="container mx-auto px-4 py-8">      <Header />    <div className="min-h-screen bg-white">  return (export default function About() {import Header from "../components/Header"import Link from "next/link"import Image from "next/image"