































































































































































}  )    </div>      </footer>        </div>          </div>            <div className="text-sm">© 2025 True North Bites. All rights reserved.</div>            </div>              </Link>                Terms of Service              <Link href="/terms-of-service" className="hover:text-red-400">              </Link>                Privacy Policy              <Link href="/privacy-policy" className="mr-4 hover:text-red-400">            <div className="mb-4 md:mb-0">          <div className="flex flex-col md:flex-row justify-between items-center">        <div className="container mx-auto px-4">      <footer className="bg-gray-800 text-white py-8">      {/* Footer */}      </section>        </div>          </div>            </div>              </div>                </Link>                  <Twitter size={32} />                >                  className="text-gray-600 hover:text-red-600 transition duration-300 transform hover:scale-110"                  rel="noopener noreferrer"                  target="_blank"                  href="https://twitter.com"                <Link                </Link>                  <Instagram size={32} />                >                  className="text-gray-600 hover:text-red-600 transition duration-300 transform hover:scale-110"                  rel="noopener noreferrer"                  target="_blank"                  href="https://instagram.com"                <Link                </Link>                  <Facebook size={32} />                >                  className="text-gray-600 hover:text-red-600 transition duration-300 transform hover:scale-110"                  rel="noopener noreferrer"                  target="_blank"                  href="https://facebook.com"                <Link              <div className="flex space-x-6">            <div className="md:w-1/2 md:pl-12 flex justify-center">            </div>              <ContactForm />            <div className="md:w-1/2 mb-8 md:mb-0">          <div className="flex flex-col md:flex-row items-center justify-between">          <h2 className="text-3xl font-bold mb-8 text-center">Get in Touch</h2>        <div className="container mx-auto px-4">      <section id="contact" className="py-16 bg-gray-100">      {/* Contact */}      </section>        </div>          </div>            </div>              </Link>                All Locations              >                className="inline-block mt-4 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 transform hover:scale-105 active:scale-95"                href="/locations"              <Link              </div>                <p>Mon-Fri: 10am - 10pm, Sat-Sun: 11am - 11pm</p>                <Clock className="text-red-600 mr-2" />              <div className="flex items-center">              </div>                <p>123 Maple Avenue, Sault Ste. Marie, ON</p>                <MapPin className="text-red-600 mr-2" />              <div className="flex items-center mb-4">            <div className="md:w-1/2 md:pl-12">            </div>              ></iframe>                loading="lazy"                allowFullScreen                style={{ border: 0 }}                height="300"                width="100%"                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2757.0583670046396!2d-84.33124218444431!3d46.521419079127424!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4d36311d78397345%3A0x7376d2d15e93c665!2s123%20Maple%20Ave%2C%20Sault%20Ste.%20Marie%2C%20ON%20P6A%206S5%2C%20Canada!5e0!3m2!1sen!2sus!4v1645564257658!5m2!1sen!2sus"              <iframe            <div className="md:w-1/2 mb-8 md:mb-0">          <div className="flex flex-col md:flex-row items-center justify-between">          <h2 className="text-3xl font-bold mb-8 text-center">Find Us</h2>        <div className="container mx-auto px-4">      <section className="py-16">      {/* Location & Hours */}      </section>        </div>          </div>            </div>              </Link>                Learn More              >                className="inline-block mt-4 bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 transform hover:scale-105 active:scale-95"                href="/about"              <Link              </p>                local ingredients, we create delicious dishes that celebrate our culinary heritage.                True North Bites is dedicated to bringing the best of Canadian fast food to our community. Using fresh,              <p className="text-gray-700 leading-relaxed">              <h2 className="text-3xl font-bold mb-4">Our Story</h2>            <div className="md:w-1/2 md:pl-12">            </div>              />                className="rounded-lg shadow-lg w-full h-auto"                height={400}                width={600}                alt="True North Bites interior"                src="https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1470&q=80"              <Image            <div className="md:w-1/2 mb-8 md:mb-0">          <div className="flex flex-col md:flex-row items-center">        <div className="container mx-auto px-4">      <section className="py-16 bg-gray-100">      {/* About Us */}      <MenuHighlights />      </section>        </div>          </Link>            View Menu          >            className="bg-red-600 hover:bg-red-700 text-white font-bold py-3 px-6 rounded-full transition duration-300 transform hover:scale-105 active:scale-95"            href="/menu"          <Link          <p className="text-xl md:text-2xl mb-8">Indulge in our authentic, locally-sourced fast food</p>          <h1 className="text-4xl md:text-6xl font-bold mb-4">Discover the True Taste of Canada</h1>        <div className="absolute inset-0 flex flex-col items-center justify-center text-white text-center px-4">        />          priority          className="brightness-50"          objectFit="cover"          layout="fill"          alt="Canadian fast food with rustic landscape"          src="https://images.unsplash.com/photo-1484723091739-30a097e8f929?auto=format&fit=crop&w=1470&q=80"        <Image      <section className="relative h-screen">      {/* Hero Section */}      <Header />    <div className="min-h-screen bg-white">  return (export default function Home() {import ContactForm from "../components/ContactForm"import MenuHighlights from "../components/MenuHighlights"import Header from "../components/Header"import { MapPin, Clock, Facebook, Instagram, Twitter } from "lucide-react"import Link from "next/link"import Image from "next/image"