




















































}  )    </div>      </main>        </div>          ))}            </div>              </div>                <p>{location.hours}</p>                <Clock className="text-red-600 mr-2 mt-1" />              <div className="flex items-start">              </div>                <p>{location.phone}</p>                <Phone className="text-red-600 mr-2" />              <div className="flex items-center mb-2">              </div>                <p>{location.address}</p>                <MapPin className="text-red-600 mr-2 mt-1" />              <div className="flex items-start mb-2">              <h2 className="text-2xl font-bold mb-4">{location.name}</h2>            <div key={index} className="bg-white rounded-lg shadow-md p-6">          {locations.map((location, index) => (        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">        <h1 className="text-4xl font-bold mb-8 text-center">Our Locations</h1>      <main className="container mx-auto px-4 py-8">      <Header />    <div className="min-h-screen bg-white">  return (export default function Locations() {]  },    hours: "Mon-Fri: 8am - 8pm, Sat: 10am - 6pm, Sun: Closed",    phone: "(705) 246-8101",    address: "789 Queen Street East, Sault Ste. Marie, ON",    name: "Algoma University",  {  },    hours: "Mon-Sun: 11am - 9pm",    phone: "(705) 987-6543",    address: "456 Lakeshore Drive, Sault Ste. Marie, ON",    name: "Waterfront",  {  },    hours: "Mon-Fri: 10am - 10pm, Sat-Sun: 11am - 11pm",    phone: "(705) 123-4567",    address: "123 Maple Avenue, Sault Ste. Marie, ON",    name: "Downtown Sault Ste. Marie",  {const locations = [import { MapPin, Phone, Clock } from "lucide-react"import Header from "../components/Header"