
































































}  )    </div>      </main>        ))}          </div>            </div>              ))}                </div>                  <p className="text-red-600 font-bold">{item.price}</p>                  <p className="text-gray-600 mb-2">{item.description}</p>                  <h3 className="text-xl font-bold mb-2">{item.name}</h3>                <div key={itemIndex} className="bg-white rounded-lg shadow-md p-6">              {category.items.map((item, itemIndex) => (            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">            <h2 className="text-3xl font-bold mb-4">{category.name}</h2>          <div key={index} className="mb-12">        {menuCategories.map((category, index) => (        <h1 className="text-4xl font-bold mb-8 text-center">Our Menu</h1>      <main className="container mx-auto px-4 py-8">      <Header />    <div className="min-h-screen bg-white">  return (export default function Menu() {]  },    ],      { name: "Maple Pecan Pie", price: "$5.99", description: "Classic pecan pie with a maple twist" },      { name: "Nanaimo Bar", price: "$4.99", description: "Layered chocolate, custard, and coconut dessert bar" },      { name: "Butter Tart Delight", price: "$3.99", description: "A rich and buttery treat that's purely Canadian" },    items: [    name: "Desserts",  {  },    ],      { name: "Smoked Meat Poutine", price: "$11.99", description: "Poutine topped with Montreal-style smoked meat" },      },        description: "Sweet potato fries with a maple syrup glaze",        price: "$6.99",        name: "Maple Glazed Sweet Potato Fries",      {      },        description: "Classic fries topped with cheese curds and savory gravy",        price: "$9.99",        name: "Poutine Supreme",      {    items: [    name: "Sides",  {  },    ],      },        description: "Burger with crispy bacon and a sweet beaver tail pastry",        price: "$13.99",        name: "Bacon Beaver Tail Burger",      {      { name: "Poutine Burger", price: "$12.99", description: "Burger topped with fries, cheese curds, and gravy" },      { name: "Maple Syrup Burger", price: "$11.99", description: "Juicy beef patty with a hint of sweet maple syrup" },    items: [    name: "Burgers",  {const menuCategories = [import Header from "../components/Header"