





































































}  )    </div>      </main>        </section>          </div>            ))}              </div>                </div>                  </Link>                    Claim Offer                  >                    className="bg-red-600 hover:bg-red-700 text-white font-bold py-2 px-4 rounded transition duration-300 transform hover:scale-105 active:scale-95"                    href="/menu"                  <Link                  <p className="text-sm text-gray-500 mb-4">Expires: {promo.expirationDate}</p>                  <p className="text-gray-600 mb-4">{promo.description}</p>                  <h2 className="text-2xl font-bold mb-2">{promo.title}</h2>                <div className="p-6">                </div>                  <Image src={promo.image || "/placeholder.svg"} alt={promo.title} layout="fill" objectFit="cover" />                <div className="relative h-48">              <div key={index} className="bg-white rounded-lg shadow-lg overflow-hidden">            {promotions.map((promo, index) => (          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">        <section className="container mx-auto px-4 py-16">        </section>          </div>            <h1 className="text-4xl md:text-6xl font-bold text-white">Special Offers</h1>          <div className="absolute inset-0 flex items-center justify-center">          />            priority            className="brightness-50"            objectFit="cover"            layout="fill"            alt="Current promotions banner"            src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1470&q=80"          <Image        <section className="relative h-64 md:h-96">      <main className="pt-16">      <Header />    <div className="min-h-screen bg-white">  return (export default function Promotions() {]  },    expirationDate: "Ongoing",    image: "https://images.unsplash.com/photo-1527690789675-4ea7d8da9fe1?auto=format&fit=crop&w=1470&q=80",    description: "Show your student ID and get 15% off your entire order!",    title: "Student Discount",  {  },    expirationDate: "February 28, 2025",    image: "https://images.unsplash.com/photo-1583967891045-3e86f5770358?auto=format&fit=crop&w=1470&q=80",    description: "Buy one poutine, get a second 50% off!",    title: "Winter Warmer Deal",  {  },    expirationDate: "July 1, 2025",    image: "https://images.unsplash.com/photo-1579954115545-a95591f28bfc?auto=format&fit=crop&w=1470&q=80",    description: "Get a free maple syrup milkshake with any burger purchase!",    title: "Canada Day Special",  {const promotions = [import Header from "../components/Header"import Link from "next/link"import Image from "next/image"